version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp:latest
    container_name: webapp
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDb;User=sa;Password=Password123;TrustServerCertificate=True
    ports:
      - "5000:80"
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=01153
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - app-network

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge
